import { STATUSES } from "../blog/blogSlice"
import { setBlog, setStatus, setTitle } from "./AISlice"
import { Configuration, OpenAIApi }  from "openai";

  const configuration = new Configuration({
    apiKey : process.env.REACT_APP_OPENAI_API_KEYS,
  });
  
  const openai = new OpenAIApi(configuration);

export function AIGenerateBlog(value){
    return async function AIGenerateThunk(dispatch,getState){
        dispatch(setStatus(STATUSES.LOADING));
        try {
          
          await new Promise((resolve,reject) => {
                  setTimeout(() => {
                    dispatch(setBlog(`Eos nemo eaque, ullam illum ex sed non unde possimus repellat quos nesciunt cum deserunt ea, mollitia ab at accusamus recusandae ipsum molestiae omnis iusto cumque vel quasi! Dignissimos eum consequatur tempora esse accusamus nobis minima aliquam quas obcaecati nihil, rem nemo, ullam consequuntur doloremque nisi, ducimus dicta.
                    Ratione mollitia maxime tempora magnam maiores eos dolor at ex dolore illum esse, aut reprehenderit odit id quam fugiat animi neque cupiditate necessitatibus. Maiores repellendus perspiciatis saepe, praesentium doloremque incidunt eaque cupiditate neque? Dolorum exercitationem sed porro ad temporibus pariatur adipisci nesciunt minus modi vitae tempora quibusdam quisquam, odio laborum, iste ullam, obcaecati qui molestiae iure tenetur nemo ab. Eligendi rem, placeat beatae magnam voluptas, distinctio quam reiciendis ipsam dolorem nihil asperiores pariatur repellendus, alias amet ab. Quo vel maiores sequi obcaecati ducimus aliquam facere animi dolorem optio. Voluptas incidunt, quas tempore tenetur ipsum consequuntur porro id vitae minus odit eos nobis, amet, maiores provident molestias vel voluptate nihil fugit molestiae esse magnam nesciunt ad non. In eius magni, voluptatibus nisi quibusdam vitae tempore nemo ducimus incidunt omnis pariatur officia doloribus exercitationem optio saepe expedita, deserunt quo facilis inventore dolorem recusandae reiciendis quidem impedit. Quasi aspernatur, soluta quidem consequatur, aliquid cumque placeat aliquam minus earum, corporis eveniet nisi alias ea. Ad at et, reiciendis consectetur blanditiis laboriosam molestias optio ab placeat exercitationem. Voluptatibus beatae eligendi sunt nam veniam eius odio maxime adipisci repellat, aspernatur nisi nemo quae saepe rem omnis quos fugiat ad quo.
                    Iste, deleniti voluptatibus! Neque consequuntur dolorem dicta ab ea architecto magnam fugit non est odio sapiente necessitatibus hic exercitationem quo aliquam unde, cupiditate animi quasi doloribus repellendus quibusdam? Ut ad quae omnis soluta, sunt repellendus nulla esse odio inventore dolorem eveniet. Voluptatem commodi magnam itaque a pariatur voluptatum sed expedita, optio nihil voluptate eos, vel quisquam, sint at tempora ipsa beatae? Cum animi sequi rerum distinctio laborum nostrum, corrupti minima fugiat numquam quae a error obcaecati quas perferendis. Assumenda provident architecto, delectus, sapiente impedit accusamus dolores voluptatum quia magnam possimus iste distinctio optio vitae ea et qui enim deserunt! Quos, cumque? Voluptates nesciunt quos magni qui minus pariatur, libero laudantium architecto magnam asperiores, nihil atque deserunt harum sequi provident eveniet ipsa nobis dicta voluptate rem saepe. Mollitia dolorum quos unde libero reiciendis architecto illum ut praesentium tempore cumque, obcaecati tempora placeat modi deserunt? Quia debitis veniam fugiat provident voluptatibus omnis, consequatur voluptate temporibus. Veritatis beatae quo, qui molestias consequuntur laborum minus minima, at excepturi voluptatum obcaecati, vero quae voluptate velit consequatur.
                     Totam dolorum numquam accusamus, ipsam placeat beatae? Quia praesentium ea ipsam, rem perspiciatis nulla libero tempora consectetur molestiae, quibusdam facilis totam dolorum maiores amet. Quod, praesentium? Cumque rerum in quasi omnis molestias velit exercitationem quidem nesciunt neque nam obcaecati debitis unde, dolorum ipsum, iste ea? Officia cupiditate consequatur atque, ad dolor repellendus quos laborum at eveniet natus quasi incidunt. Laborum ipsam iste, cupiditate ut non ex minima quis incidunt sunt animi nulla alias quasi eum vel cum? Nulla adipisci laudantium amet dignissimos alias magni, dolore quisquam asperiores fugiat eius commodi error vitae ullam, blanditiis eaque impedit mollitia omnis eos illum quae! Est, nulla? Aspernatur voluptas, dolore omnis nihil autem asperiores iste incidunt magnam provident voluptates. Quae magnam officiis et commodi corrupti autem, pariatur, aperiam repudiandae nostrum ipsam culpa consectetur quia maiores excepturi voluptatibus sint nam, explicabo mollitia aut dolores numquam! Neque, quibusdam debitis! Deserunt libero laboriosam optio sint vel neque, exercitationem officia minus eveniet, rerum perferendis harum dicta. Rem eveniet atque libero voluptate aliquid quo. Sequi reprehenderit nulla dolorem placeat totam hic laborum in cupiditate itaque natus ducimus, cumque aut architecto, molestias iusto suscipit at inventore tempora esse quidem rerum! Officia cumque porro quibusdam, assumenda.
                    olorum exercitationem esse dolorem ab necessitatibus commodi! Qui temporibus, officia, fugiat aliquam quidem doloremque neque quibusdam asperiores harum aliquid quae, assumenda porro. Voluptatibus saepe illum architecto error sed dolorem aperiam recusandae nesciunt nostrum deserunt magni cum pariatur quis quo assumenda blanditiis, consectetur, odit aliquid ea. Error nihil quos tenetur totam quasi voluptatibus accusamus officiis cumque aliquam architecto iure repellendus alias tempora minima, modi consequuntur accusantium nostrum voluptatem nulla quia repudiandae eos adipisci? Ducimus quo sit voluptas quas et dolorum a in, perferendis provident. Optio ut voluptates molestias laboriosam, consequuntur voluptas tempora eaque sint officiis cum deserunt ab molestiae. Vel qui possimus aspernatur recusandae, numquam error similique sapiente, consectetur autem et porro. Eveniet cumque inventore placeat illo fugit vero distinctio, deleniti accusamus blanditiis soluta quidem nulla dolore ducimus cum culpa ipsam dicta vel consequatur quasi! Vitae suscipit eligendi, earum, ratione aspernatur culpa consequatur atque ab totam, rem voluptate illum. Aperiam ipsum odio possimus adipisci nulla eaque esse iusto, molestias qui repudiandae repellendus enim rerum consequuntur quo, rem placeat aut tempora distinctio quas a atque, dignissimos ipsam magnam ut! Vel asperiores, natus dolor, dolore mollitia cumque porro blanditiis repudiandae, laudantium officia nobis voluptate neque fugit autem consequuntur facilis quos? Cupiditate repellat magni nobis vel aliquid, blanditiis molestiae magnam deserunt eveniet debitis? Explicabo iure sunt voluptatum nemo, tenetur eius modi veritatis consequuntur praesentium eveniet, deleniti ipsum? Eligendi corrupti natus dolorum adipisci ipsam. Eos aspernatur sit saepe perspiciatis molestias similique, dolore voluptatem voluptas vel molestiae.
                     obcaecati error quos magni eum laborum consectetur tempore suscipit delectus nulla doloremque laudantium tempora? Eum iusto officiis doloribus soluta quam dignissimos quia, omnis necessitatibus molestiae voluptatum praesentium at assumenda eos, facere maxime et? Assumenda nisi quaerat consequuntur deleniti et veritatis ipsum quam obcaecati laborum dicta. Vel odit quae vero quas, possimus ab ratione ad natus et, ex totam nemo, eius illum sed aperiam numquam expedita earum! Laboriosam aperiam ducimus suscipit vel placeat, laborum eligendi, eos, nam explicabo repellendus et! Asperiores voluptate laudantium corporis dolore placeat fugit, animi distinctio perspiciatis nulla in nemo autem recusandae iste ipsum error veritatis architecto hic numquam unde ipsam odio aspernatur eveniet. Minus sed enim recusandae excepturi nobis? Aliquid consequuntur nihil aspernatur blanditiis esse, distinctio praesentium sint maiores cumque veniam eum reprehenderit debitis voluptatibus officiis voluptas totam incidunt. Laborum animi quo deleniti architecto vero, aspernatur ex nisi molestiae rerum aperiam quae veritatis aliquam. Eveniet accusantium blanditiis veritatis natus non ipsam in beatae ipsum amet tempora a numquam aliquam rem iusto voluptates aut asperiores quaerat sit sapiente, similique vero nulla. Enim natus quasi suscipit ratione quas consequatur nesciunt voluptatibus sit ex molestias totam ducimus quisquam iure fugit odio impedit, nisi, aliquam quia. Quas labore doloremque eaque temporibus possimus expedita quod ducimus autem soluta consequuntur molestiae non voluptas odio, neque dicta quaerat vel laborum id iste corporis vitae nesciunt molestias ipsum! Deleniti, velit animi! Recusandae necessitatibus consequatur quaerat possimus suscipit minus ipsum, voluptas, nulla dolor iure quia, autem dicta harum placeat dolorum laudantium praesentium cumque corrupti. Natus nesciunt ipsum harum eaque perferendis iure deserunt quisquam optio porro modi! Voluptas quod nobis labore corporis.
                      soluta iste molestiae consequuntur in fuga officia delectus commodi, assumenda rerum obcaecati exercitationem! Cupiditate tempore, omnis eius nisi voluptatum minus numquam error, hic voluptates voluptate dolorem placeat eos quam nam fugit? Aperiam cumque quisquam exercitationem! Omnis ipsa id perferendis illum nesciunt, eligendi quae debitis, fugiat a adipisci animi dignissimos iure fuga ullam vel numquam vero labore ut, dolores pariatur necessitatibus temporibus eius aliquid illo! Iure cupiditate ducimus deleniti? Itaque quisquam minus corrupti esse ullam corporis. Eveniet harum quasi laudantium, corporis minus fuga in eius quis enim aperiam et numquam unde ratione reprehenderit libero quaerat, autem iure. Ducimus, harum, reprehenderit doloribus aspernatur distinctio quas cumque quidem atque veniam officiis, minima debitis! Nisi obcaecati dolorem rem quis autem nemo deleniti iure delectus, necessitatibus doloribus ea eligendi, praesentium veniam reprehenderit mollitia vitae, debitis aliquid qui dolore amet sint! Veritatis magnam asperiores, nihil fuga natus excepturi, iure voluptatibus cumque reprehenderit nemo tempore voluptate in itaque aliquam dolores optio necessitatibus totam porro. Quidem hic laborum, numquam rerum aperiam minima harum modi libero est eos dignissimos. Fuga autem beatae natus excepturi nisi optio, rerum soluta nihil, quos eveniet temporibus distinctio in iste doloremque fugit! Inventore maxime harum nesciunt dolore provident. Officia numquam illum dolorem porro animi, amet molestias voluptatibus assumenda voluptate aperiam in cumque itaque facilis consectetur ipsa nihil blanditiis quisquam id ab temporibus, tempora veniam mollitia! Error, perspiciatis aspernatur similique.
                       facere natus architecto consequatur rerum minima quasi maxime consectetur, quidem tempora modi facilis dolores illum animi? Cum quo ex, saepe eum consequuntur unde fuga voluptas error tempora, itaque officia neque consectetur veniam fugiat natus dolore. Officia inventore quis officiis neque laboriosam alias, cupiditate, esse nemo aliquam libero rerum excepturi. Nostrum quis reprehenderit accusamus maxime provident natus assumenda, voluptatum, quibusdam eius beatae nihil sed, delectus consectetur. Soluta aut laborum perferendis ipsam, in dolorum ea corporis totam beatae debitis ut id fugit eum nulla accusamus, repellendus fugiat commodi, vero fuga doloremque incidunt? Architecto assumenda earum, nostrum excepturi repudiandae ipsam sunt dicta laboriosam corporis reiciendis minus culpa deserunt repellat est placeat. Incidunt vel corporis, odio cumque excepturi aliquam optio labore eius rerum error ipsam doloremque hic doloribus temporibus molestias, iste earum! Modi, voluptates libero? Esse architecto laborum dolorem quis recusandae libero illo accusamus voluptate quo perferendis neque minus non repellendus vel fugiat, fugit facere assumenda perspiciatis mollitia, porro culpa exercitationem accusantium maxime? Perspiciatis velit repellendus cumque rem suscipit error, ipsa tempora blanditiis? Rem nostrum quod nemo? Tempore esse, repudiandae, est atque architecto delectus unde voluptate temporibus, exercitationem consequuntur aliquam rem.
                       exercitationem sed enim, nemo non. Adipisci accusantium asperiores sint nam eveniet inventore doloribus, molestiae facere cupiditate nesciunt labore numquam dolore repudiandae ad vitae officiis unde cum voluptas corporis mollitia recusandae totam quas rerum? Velit suscipit pariatur temporibus, laudantium cumque quisquam doloribus dolores ipsam veritatis alias possimus sequi eos totam assumenda laborum nulla quasi sit illo repellendus eum incidunt iusto esse beatae eius. Autem quaerat suscipit labore nemo dolore odit, quibusdam incidunt quisquam rem quis accusantium provident eligendi harum facere perspiciatis? Id explicabo accusantium maiores dolores eius facere voluptatem impedit, dolorum modi laudantium ea fugit placeat iste minus vel autem eveniet voluptate at quasi tenetur optio obcaecati amet! Sed voluptatum veniam nesciunt maiores libero non. Necessitatibus beatae voluptatibus, at quam sit ad. Facere possimus repellendus quam, voluptas minima hic nobis, rem, qui reiciendis nihil laborum mollitia. Qui, eveniet facilis? Odio dolore reprehenderit excepturi? Excepturi ipsam a asperiores porro eos voluptatibus consequuntur, recusandae totam iusto aliquid repellendus nesciunt unde hic ab rem qui ea est iure quos rerum beatae eveniet libero distinctio. Voluptas itaque necessitatibus accusantium nobis, reprehenderit quasi corporis eos, ullam dignissimos incidunt ipsum? Doloremque ea, ratione voluptatem aperiam dolorum impedit nam, deleniti quas nobis alias cumque.
                        commodi reprehenderit? Accusantium nesciunt debitis ipsam eius error a tempore impedit at possimus, minus dolorum. earum placeat voluptas! Inventore tempora eius voluptates modi doloremque, aperiam harum quam quo sit nisi vel, possimus impedit mollitia a nesciunt perspiciatis numquam enim unde et porro! Debitis quo ex corrupti, veritatis vel dolor excepturi amet illo dolore nulla eaque dolores id suscipit eligendi culpa tempore dicta voluptas aliquam expedita libero deleniti voluptatibus vitae. Reiciendis sunt aut veniam odio fugit molestiae accusantium sit adipisci inventore sed necessitatibus illum fuga sequi vel earum aliquam facere aspernatur cupiditate, quibusdam aperiam error quo est neque nemo? Amet, saepe eos illum repellendus possimus similique quaerat ipsa voluptatum autem reprehenderit quos voluptates facere at aspernatur odio, blanditiis fugit! Quaerat soluta eum praesentium omnis culpa veritatis ut consequuntur? Alias sed ducimus tempora, nam animi assumenda laborum aut cupiditate odio doloribus facilis quae voluptatem quo tempore quasi adipisci eius corporis temporibus. Voluptate cumque quam inventore vero tempora possimus perspiciatis? Ut, ea omnis atque, quis earum animi est cumque, tempore amet rerum cum laudantium quasi tenetur tempora quisquam. Consequuntur, harum, pariatur ad deserunt itaque velit laborum eaque amet voluptatum tempora corporis magni obcaecati et sapiente id? Ut sapiente dolores commodi laboriosam recusandae.
                        , eligendi magni dignissimos odio nihil explicabo delectus ipsum et repudiandae, voluptates libero magnam, vel earum aliquid dicta doloribus eum esse veritatis ipsa! Quasi illo, dolores possimus ratione cupiditate nesciunt rerum rem necessitatibus quis quos eum ullam dicta, blanditiis non eius ad similique quo. Hic cupiditate excepturi eius amet voluptatum praesentium aut labore ad obcaecati voluptate quisquam facere at similique delectus et. eos, ab voluptas! Iste mollitia omnis pariatur incidunt illo laborum assumenda neque, vel, quo amet, dicta minima error voluptate veniam sunt veritatis rem? Accusantium officiis libero fugiat voluptatibus quod, quisquam optio labore. Ipsa veritatis cum repellendus esse repellat. Quisquam facilis asperiores laudantium labore optio. Voluptate vero dolorum vel necessitatibus, iure veritatis magnam sed neque fugiat nam ratione, quam facere culpa debitis dolores nihil accusamus atque! Dolor accusamus consequatur corporis dignissimos voluptatibus quam veniam nemo architecto. Repudiandae hic perferendis quas, nisi debitis qui error quae, odio vel fuga eveniet voluptatibus voluptatem ex maiores voluptatum quasi adipisci atque. Placeat provident aut qui ut libero dolorem sed, ratione cum eveniet fuga nam dicta! Ex, adipisci. Totam sed asperiores in doloremque, debitis fugit at explicabo minus quibusdam, impedit ex laboriosam amet, inventore corporis et corrupti beatae reprehenderit repellat libero nam dolores dolorem. Mollitia, fugit doloremque ullam accusantium repellendus odit earum, quae impedit nemo animi eum pariatur adipisci tenetur? Eaque adipisci repellendus, aperiam vitae nam ex, accusamus soluta mollitia aut, necessitatibus veritatis? Distinctio accusantium aperiam earum consequatur dolorem culpa nisi praesentium debitis mollitia harum provident illo perferendis cumque, libero odio enim quod doloribus in? Deserunt quis distinctio dignissimos. Ad, impedit tempore iusto voluptates corrupti nam laudantium po.
                       ssimus quae eveniet molestias quibusdam, minima minus deserunt. Dolore, corrupti est maxime blanditiis, asperiores quo ab enim possimus, ratione distinctio quas? Quae ut architecto fugiat perferendis optio nemo eos, quis non minima sed in! Laborum aliquam illum reprehenderit odit quasi debitis adipisci itaque perspiciatis unde non facilis, officia hic fugiat libero dolore quae voluptate incidunt iure voluptatibus nobis. Eum odio cum ullam nam a, maxime praesentium culpa autem fugiat vero quisquam. Perferendis neque tempora, deserunt cupiditate repudiandae delectus porro. Temporibus, quo debitis officia ex, corporis earum quam animi est reiciendis pariatur consequuntur facere itaque. Suscipit, iste quis ad et dicta consequuntur quisquam dolorem!
                    `));
                    resolve();
                    dispatch(setStatus(STATUSES.SUCCESS));
              }, 2000);
          });

            // const res = await openai.createCompletion({
            //     model: "text-davinci-003",
            //     prompt: `Generate a blog on a topic ${value}`,
            //     temperature: 0.8,
            //     max_tokens: 1000,
            //     top_p: 1,
            //     frequency_penalty: 0,
            //     presence_penalty: 0,
            //   });

            // console.log(res);
            // dispatch(setBlog(res.data.choices[0].text));
            // dispatch(setStatus(STATUSES.SUCCESS));
            
        } catch (error) {
            console.log(error);
            dispatch(setStatus(STATUSES.ERROR));
        }
    }
}


export function AIGenerateTitle(value){
  return async function AIGenerateThunk(dispatch,getState){
      dispatch(setStatus(STATUSES.LOADING));
      try {
        
        await new Promise((resolve,reject) => {
                setTimeout(() => {
                  dispatch(setTitle(`
                    1. Exploring the Benefits of Backend Technologies for Web Development
                    2. Introduction to the Basics of Backend Development
                    3. Investigating the Latest Trends in Backend Technologies
                    4. Understanding the Advantages of Serverless Computing
                    5. Building Your First Backend Service with NodeJS
                    6. Automating Your Backend Development with Cloud Services
                    7. Securing Your Backend Services with Authentication and Authorization
                    8. What Are the Best Practices for Database Design?
                    9. Optimizing Performance of Your Backend System
                    10. Building Scalable Backend Services with Microservices
                    11. Troubleshooting Common Issues with Backend Technologies
                    12. Scaling Your Backend Services for Maximum Efficiency
                    13. Exploring the Benefits of GraphQL for Backend Development
                    14. Picking the Right Backend Technology for Your Project
                  `));
                  dispatch(setStatus(STATUSES.SUCCESS));
                  resolve();
            }, 2000);
        });

          // const res = await openai.createCompletion({
          //     model: "text-davinci-003",
          //     prompt: `Genrate 10+ blog titles on a topic ${value}`,
          //     temperature: 0.8,
          //     max_tokens: 200,
          //     top_p: 1,
          //     frequency_penalty: 0,
          //     presence_penalty: 0,
          //   });

          // console.log(res);
          // dispatch(setTitle(res.data.choices[0].text));
          // dispatch(setStatus(STATUSES.SUCCESS));
          
      } catch (error) {
          console.log(error);
          dispatch(setStatus(STATUSES.ERROR));
      }
  }
}
